apiVersion: v1 
kind: Service 
metadata: 
  name: crds-graphql-gateway
  namespace: api
  labels: 
    app: crds-graphql-gateway
spec: 
  ports: 
  - name: node
    port: 80
    targetPort: 8000
  selector:
    app: graphql-gateway
